INSERT INTO circuits (circuitid, circuitRef, name, location, country) VALUES (1, 'albert_park', 'Albert Park Grand Prix Circuit', 'Melbourne', 'Australia');
INSERT INTO circuits (circuitid, circuitRef, name, location, country) VALUES (2, 'sepang', 'Sepang International Circuit', 'Kuala Lumpur', 'Malaysia');
INSERT INTO circuits (circuitid, circuitRef, name, location, country) VALUES (3, 'bahrain', 'Bahrain International Circuit', 'Sakhir', 'Bahrain');
INSERT INTO circuits (circuitid, circuitRef, name, location, country) VALUES (4, 'catalunya', 'Circuit de Barcelona-Catalunya', 'MontmelÃ³', 'Spain');
INSERT INTO circuits (circuitid, circuitRef, name, location, country) VALUES (5, 'istanbul', 'Istanbul Park', 'Istanbul', 'Turkey');
INSERT INTO circuits (circuitid, circuitRef, name, location, country) VALUES (6, 'monaco', 'Circuit de Monaco', 'Monte-Carlo', 'Monaco');
INSERT INTO circuits (circuitid, circuitRef, name, location, country) VALUES (7, 'villeneuve', 'Circuit Gilles Villeneuve', 'Montreal', 'Canada');
INSERT INTO circuits (circuitid, circuitRef, name, location, country) VALUES (8, 'magny_cours', 'Circuit de Nevers Magny-Cours', 'Magny Cours', 'France');
INSERT INTO circuits (circuitid, circuitRef, name, location, country) VALUES (9, 'silverstone', 'Silverstone Circuit', 'Silverstone', 'UK');
INSERT INTO circuits (circuitid, circuitRef, name, location, country) VALUES (10, 'hockenheimring', 'Hockenheimring', 'Hockenheim', 'Germany');
INSERT INTO circuits (circuitid, circuitRef, name, location, country) VALUES (11, 'hungaroring', 'Hungaroring', 'Budapest', 'Hungary');
INSERT INTO circuits (circuitid, circuitRef, name, location, country) VALUES (12, 'valencia', 'Valencia Street Circuit', 'Valencia', 'Spain');
INSERT INTO circuits (circuitid, circuitRef, name, location, country) VALUES (13, 'spa', 'Circuit de Spa-Francorchamps', 'Spa', 'Belgium');
INSERT INTO circuits (circuitid, circuitRef, name, location, country) VALUES (14, 'monza', 'Autodromo Nazionale di Monza', 'Monza', 'Italy');
INSERT INTO circuits (circuitid, circuitRef, name, location, country) VALUES (15, 'marina_bay', 'Marina Bay Street Circuit', 'Marina Bay', 'Singapore');
INSERT INTO circuits (circuitid, circuitRef, name, location, country) VALUES (16, 'fuji', 'Fuji Speedway', 'Oyama', 'Japan');
INSERT INTO circuits (circuitid, circuitRef, name, location, country) VALUES (17, 'shanghai', 'Shanghai International Circuit', 'Shanghai', 'China');
INSERT INTO circuits (circuitid, circuitRef, name, location, country) VALUES (18, 'interlagos', 'AutÃ³dromo JosÃ© Carlos Pace', 'SÃ£o Paulo', 'Brazil');
INSERT INTO circuits (circuitid, circuitRef, name, location, country) VALUES (19, 'indianapolis', 'Indianapolis Motor Speedway', 'Indianapolis', 'USA');
INSERT INTO circuits (circuitid, circuitRef, name, location, country) VALUES (20, 'nurburgring', 'NÃ¼rburgring', 'NÃ¼rburg', 'Germany');
INSERT INTO circuits (circuitid, circuitRef, name, location, country) VALUES (21, 'imola', 'Autodromo Enzo e Dino Ferrari', 'Imola', 'Italy');
INSERT INTO circuits (circuitid, circuitRef, name, location, country) VALUES (22, 'suzuka', 'Suzuka Circuit', 'Suzuka', 'Japan');
INSERT INTO circuits (circuitid, circuitRef, name, location, country) VALUES (80, 'vegas', 'Las Vegas Strip Street Circuit', 'Las Vegas', 'United States');
INSERT INTO circuits (circuitid, circuitRef, name, location, country) VALUES (24, 'yas_marina', 'Yas Marina Circuit', 'Abu Dhabi', 'UAE');
INSERT INTO circuits (circuitid, circuitRef, name, location, country) VALUES (25, 'galvez', 'AutÃ³dromo Juan y Oscar GÃ¡lvez', 'Buenos Aires', 'Argentina');
INSERT INTO circuits (circuitid, circuitRef, name, location, country) VALUES (26, 'jerez', 'Circuito de Jerez', 'Jerez de la Frontera', 'Spain');
INSERT INTO circuits (circuitid, circuitRef, name, location, country) VALUES (27, 'estoril', 'AutÃ³dromo do Estoril', 'Estoril', 'Portugal');
INSERT INTO circuits (circuitid, circuitRef, name, location, country) VALUES (28, 'okayama', 'Okayama International Circuit', 'Okayama', 'Japan');
INSERT INTO circuits (circuitid, circuitRef, name, location, country) VALUES (29, 'adelaide', 'Adelaide Street Circuit', 'Adelaide', 'Australia');
INSERT INTO circuits (circuitid, circuitRef, name, location, country) VALUES (30, 'kyalami', 'Kyalami', 'Midrand', 'South Africa');
INSERT INTO circuits (circuitid, circuitRef, name, location, country) VALUES (31, 'donington', 'Donington Park', 'Castle Donington', 'UK');
INSERT INTO circuits (circuitid, circuitRef, name, location, country) VALUES (32, 'rodriguez', 'AutÃ³dromo Hermanos RodrÃ­guez', 'Mexico City', 'Mexico');
INSERT INTO circuits (circuitid, circuitRef, name, location, country) VALUES (33, 'phoenix', 'Phoenix street circuit', 'Phoenix', 'USA');
INSERT INTO circuits (circuitid, circuitRef, name, location, country) VALUES (34, 'ricard', 'Circuit Paul Ricard', 'Le Castellet', 'France');
INSERT INTO circuits (circuitid, circuitRef, name, location, country) VALUES (35, 'yeongam', 'Korean International Circuit', 'Yeongam County', 'Korea');
INSERT INTO circuits (circuitid, circuitRef, name, location, country) VALUES (36, 'jacarepagua', 'AutÃ³dromo Internacional Nelson Piquet', 'Rio de Janeiro', 'Brazil');
INSERT INTO circuits (circuitid, circuitRef, name, location, country) VALUES (37, 'detroit', 'Detroit Street Circuit', 'Detroit', 'USA');
INSERT INTO circuits (circuitid, circuitRef, name, location, country) VALUES (38, 'brands_hatch', 'Brands Hatch', 'Kent', 'UK');
INSERT INTO circuits (circuitid, circuitRef, name, location, country) VALUES (39, 'zandvoort', 'Circuit Park Zandvoort', 'Zandvoort', 'Netherlands');
INSERT INTO circuits (circuitid, circuitRef, name, location, country) VALUES (40, 'zolder', 'Zolder', 'Heusden-Zolder', 'Belgium');
INSERT INTO circuits (circuitid, circuitRef, name, location, country) VALUES (41, 'dijon', 'Dijon-Prenois', 'Dijon', 'France');
INSERT INTO circuits (circuitid, circuitRef, name, location, country) VALUES (42, 'dallas', 'Fair Park', 'Dallas', 'USA');
INSERT INTO circuits (circuitid, circuitRef, name, location, country) VALUES (43, 'long_beach', 'Long Beach', 'California', 'USA');
INSERT INTO circuits (circuitid, circuitRef, name, location, country) VALUES (44, 'las_vegas', 'Las Vegas Street Circuit', 'Nevada', 'USA');
INSERT INTO circuits (circuitid, circuitRef, name, location, country) VALUES (45, 'jarama', 'Jarama', 'Madrid', 'Spain');
INSERT INTO circuits (circuitid, circuitRef, name, location, country) VALUES (46, 'watkins_glen', 'Watkins Glen', 'New York State', 'USA');
INSERT INTO circuits (circuitid, circuitRef, name, location, country) VALUES (47, 'anderstorp', 'Scandinavian Raceway', 'Anderstorp', 'Sweden');
INSERT INTO circuits (circuitid, circuitRef, name, location, country) VALUES (48, 'mosport', 'Mosport International Raceway', 'Ontario', 'Canada');
INSERT INTO circuits (circuitid, circuitRef, name, location, country) VALUES (49, 'montjuic', 'MontjuÃ¯c', 'Barcelona', 'Spain');
INSERT INTO circuits (circuitid, circuitRef, name, location, country) VALUES (50, 'nivelles', 'Nivelles-Baulers', 'Brussels', 'Belgium');
INSERT INTO circuits (circuitid, circuitRef, name, location, country) VALUES (51, 'charade', 'Charade Circuit', 'Clermont-Ferrand', 'France');
INSERT INTO circuits (circuitid, circuitRef, name, location, country) VALUES (52, 'tremblant', 'Circuit Mont-Tremblant', 'Quebec', 'Canada');
INSERT INTO circuits (circuitid, circuitRef, name, location, country) VALUES (53, 'essarts', 'Rouen-Les-Essarts', 'Rouen', 'France');
INSERT INTO circuits (circuitid, circuitRef, name, location, country) VALUES (54, 'lemans', 'Le Mans', 'Le Mans', 'France');
INSERT INTO circuits (circuitid, circuitRef, name, location, country) VALUES (55, 'reims', 'Reims-Gueux', 'Reims', 'France');
INSERT INTO circuits (circuitid, circuitRef, name, location, country) VALUES (56, 'george', 'Prince George Circuit', 'Eastern Cape Province', 'South Africa');
INSERT INTO circuits (circuitid, circuitRef, name, location, country) VALUES (57, 'zeltweg', 'Zeltweg', 'Styria', 'Austria');
INSERT INTO circuits (circuitid, circuitRef, name, location, country) VALUES (58, 'aintree', 'Aintree', 'Liverpool', 'UK');
INSERT INTO circuits (circuitid, circuitRef, name, location, country) VALUES (59, 'boavista', 'Circuito da Boavista', 'Oporto', 'Portugal');
INSERT INTO circuits (circuitid, circuitRef, name, location, country) VALUES (60, 'riverside', 'Riverside International Raceway', 'California', 'USA');
INSERT INTO circuits (circuitid, circuitRef, name, location, country) VALUES (61, 'avus', 'AVUS', 'Berlin', 'Germany');
INSERT INTO circuits (circuitid, circuitRef, name, location, country) VALUES (62, 'monsanto', 'Monsanto Park Circuit', 'Lisbon', 'Portugal');
INSERT INTO circuits (circuitid, circuitRef, name, location, country) VALUES (63, 'sebring', 'Sebring International Raceway', 'Florida', 'USA');
INSERT INTO circuits (circuitid, circuitRef, name, location, country) VALUES (64, 'ain-diab', 'Ain Diab', 'Casablanca', 'Morocco');
INSERT INTO circuits (circuitid, circuitRef, name, location, country) VALUES (65, 'pescara', 'Pescara Circuit', 'Pescara', 'Italy');
INSERT INTO circuits (circuitid, circuitRef, name, location, country) VALUES (66, 'bremgarten', 'Circuit Bremgarten', 'Bern', 'Switzerland');
INSERT INTO circuits (circuitid, circuitRef, name, location, country) VALUES (67, 'pedralbes', 'Circuit de Pedralbes', 'Barcelona', 'Spain');
INSERT INTO circuits (circuitid, circuitRef, name, location, country) VALUES (68, 'buddh', 'Buddh International Circuit', 'Uttar Pradesh', 'India');
INSERT INTO circuits (circuitid, circuitRef, name, location, country) VALUES (69, 'americas', 'Circuit of the Americas', 'Austin', 'USA');
INSERT INTO circuits (circuitid, circuitRef, name, location, country) VALUES (70, 'red_bull_ring', 'Red Bull Ring', 'Spielberg', 'Austria');
INSERT INTO circuits (circuitid, circuitRef, name, location, country) VALUES (71, 'sochi', 'Sochi Autodrom', 'Sochi', 'Russia');
INSERT INTO circuits (circuitid, circuitRef, name, location, country) VALUES (73, 'baku', 'Baku City Circuit', 'Baku', 'Azerbaijan');
INSERT INTO circuits (circuitid, circuitRef, name, location, country) VALUES (75, 'portimao', 'AutÃ³dromo Internacional do Algarve', 'PortimÃ£o', 'Portugal');
INSERT INTO circuits (circuitid, circuitRef, name, location, country) VALUES (76, 'mugello', 'Autodromo Internazionale del Mugello', 'Mugello', 'Italy');
INSERT INTO circuits (circuitid, circuitRef, name, location, country) VALUES (77, 'jeddah', 'Jeddah Corniche Circuit', 'Jeddah', 'Saudi Arabia');
INSERT INTO circuits (circuitid, circuitRef, name, location, country) VALUES (78, 'losail', 'Losail International Circuit', 'Al Daayen', 'Qatar');
INSERT INTO circuits (circuitid, circuitRef, name, location, country) VALUES (79, 'miami', 'Miami International Autodrome', 'Miami', 'USA');
